const pickupLines = [
    "Are you French? Because Eiffel for you.",
    "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
    "Are you a magician? Because every time I look at you, everyone else disappears.",
    "Do you have a name, or can I call you mine?",
    "Are we at an airport? Because my heart is taking off.",
    "Are you a parking ticket? Because you’ve got FINE written all over you.",
    "You must be Wi-Fi, because I’m feeling a strong connection.",
    "You must be made of copper and tellurium, because you're Cu-Te.",
    "Are you an angel? Because heaven is missing one.",
    "Excuse me, but I think you dropped something: My jaw.",
    "Are you a time traveler? Because I see you in my future.",
    "Is your name Chapstick? Because you’re on my lips.",
    "Are you a campfire? Because you’re hot and I want s’more.",
    "Do you believe in love at first sight, or should I walk by again?",
    "You must be a keyboard, because you're just my type.",
    "If beauty were time, you’d be an eternity.",
    "Do you like raisins? How about a date?",
    "Are you a cloud? Because you make my day brighter.",
    "Are you from Tennessee? Because you’re the only ten I see.",
    "Is your name Google? Because you’ve got everything I’ve been searching for."
];

const rizzLines = [
   "I love your lips; I don't know if you have some room in your mouth for another tongue.",
    "I'm not Quavo, and I'm not here to get you Offset, but if I Takeoff, I swear you won't let Migo.",
    "I know you don't love math, but I'd love to teach you some hidden facts. How about you come to my house where we add the bed, subtract our clothes, divide our legs, then multiply?",
    "Are you not tired of adulthood? Why don't you come and be my baby 🥹🥺.",
    "Close your eyes. What did you see? If it's nothing, that's definitely how your future is without me by your side.",
    "I'm like a roller coaster—the faster I go, the more you scream.",
    "I'm not Rapunzel, but you can pull my hair while I scream your name, baby.",
    "Can you drive? Because you won't need a driving license to drive me.",
    "I need your Snap ID or TikTok handle so we can go from exchanging streaks to exchanging strokes.",
    "Hey, you look so beautiful, but I'm sorry—I want to ask if you have time to talk about how attractive you are.",
    "You know, if a thousand poets spent a thousand years writing poems, I don't think they'd capture the beauty I see in you.",
    "You ain't Christabel, but your name rings a bell.",
    "Are you single? Because I notice every single thing about you is on point.",
    "Well, my name is Têmí, but people call me Headboy because if you go home with me now, as expected, you'll expect head.",
    "Hey, I like the fact that you're very pretty, and I'd love to make you my sweetie. So, can I have your handle?",
    "I don't know why everywhere seems to be hot. Ohhh, I get it—everyone here's hot, that's why the room is hot."
    "Call me a magician, because I’m about to make your number appear in my phone.",
    "You don’t need a compass, because you’ve already found the way to my heart.",
    "I heard you like bad boys—good thing I’m bad at everything.",
    "You like coffee? Because I’ll make you my daily grind.",
    "You must be an equation, because every time I see you, my solution is always you.",
    "I’d follow you anywhere, even if it meant getting lost in your eyes.",
    "You must be a poet, because you’ve written yourself all over my heart.",
    "I don’t need directions—your smile is the only landmark I need.",
    "Are you a villain? Because you just stole my heart.",
    "I’m not a photographer, but I can picture us together.",
    "You must be a dream, because I don’t want to wake up.",
    "You’re like my favorite song—I can’t get you out of my head.",
    "If I had a dollar for every time I thought about you, I’d be a billionaire.",
    "You're so stunning, even my phone autocorrects 'perfect' to your name.",
    "If loving you is wrong, I don’t want to be right.",
    "Your smile is my favorite notification.",
    "I might not be a genie, but I can make your dreams come true.",
    "Can I borrow your heart? I promise I’ll give it back—eventually.",
    "Do you play chess? Because you just took my king down with your beauty.",
    "You must be a lucky charm, because my life is better with you in it."
];

module.exports = { pickupLines, rizzLines }
